### PR TITLE
Issue 8012: Regular Expression DoS

### LINKED ISSUE #8012: Firebug 2.0.16 - Regular Expression DoS
## Firebug 2.0.16 - Regular Expression DoS

**---------------------------------------------
I. DESCRIPTION
---------------------------------------------**

Regular Expression DoS vulnerability in Firebug 2.0.16 allows remote attackers to crash Firebug plugin.

**---------------------------------------------
II. LOCATION OF VULNERABILITY
---------------------------------------------**

Path: /firebug/content/lib/url.js
Line: 450

**---------------------------------------------
III. PROOF OF CONCEPT
---------------------------------------------**

_Tested on:_
Mozilla Firefox 45.0.1 with Firebug 2.0.16

Example URL with Evil Payload which exploits vulnerability and in result will crash Firebug plugin.

Payload: test//;../../../test

_Option I:_

1. Open URL: http://prevenity.com/?falsevariable=test;//;../../../test
2. Load Firebug plugin.

_Option II:_

1. Open Firebug plugin.
2. Open URL: http://prevenity.com/?falsevariable=test;//;../../../test

_Explanation:_
Payload works in any domain (prevenity.com is only example), we only need to put payload in value of any variable.

**---------------------------------------------
IV. REFERENCES
---------------------------------------------**

* https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

---------------------------------------------

_Discovered by: Artur Czyz (Company: Prevenity, E-Mail: vr@prevenity.com, Website: www.prevenity.com)_

### PR DESCRIPTION
**Pull request by simonlindholm**
Fixes #8012.

### CODE REVIEW

File: extension/content/firebug/lib/url.js [hunk 1]
```diff
@@ -417,7 +417,7 @@ Url.normalizeURL = function(url)
 
     // Normalize path traversals (a/b/../c -> a/c).
     while (url.indexOf("/../") !== -1 && url[0] != "/")
-        url = url.replace(/[^\/]+\/\.\.\//g, "");
+        url = url.replace(/[^\/]+\/+\.\.\//g, "");
```
Comment (janodvarko) [inline extension/content/firebug/lib/url.js]: Thanks for quick patch!

I am getting: http://prevenity.com/test
From: http://prevenity.com/?falsevariable=test;//;../../../test
While better would probably be: http://prevenity.com/

But, the original infinite loop is gone and that's what the report is about.
Honza
